# Generated by Django 2.2.5 on 2022-09-05 12:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('profile_picture', models.URLField(null=True)),
                ('cover_picture', models.URLField(null=True)),
                ('about', models.CharField(max_length=200, null=True)),
                ('level', models.CharField(max_length=200, null=True)),
                ('interested_type', models.CharField(max_length=200, null=True)),
                ('interested_cuisine', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('servings', models.CharField(max_length=5)),
                ('prep_time', models.CharField(max_length=5)),
                ('calories', models.IntegerField(blank=True)),
                ('carbs', models.FloatField(blank=True)),
                ('fat', models.FloatField(blank=True)),
                ('protein', models.FloatField(blank=True)),
                ('gluten_free', models.BooleanField(null=True)),
                ('vegan', models.BooleanField(null=True)),
                ('veggie', models.BooleanField(null=True)),
                ('very_healthy', models.BooleanField(null=True)),
                ('kind', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
                ('cusine', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
                ('occasion', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='main.Ingredient')),
            ],
        ),
    ]
