# Generated by Django 2.2.5 on 2022-09-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='kind',
            new_name='type',
        ),
    ]
